### PR TITLE
Bors: Fix job names

### PR DESCRIPTION
**Pull request by mkroening**

### CODE REVIEW

**Review by stlankes — APPROVED** [review]
bors r+

**Comment by mkroening** [comment]
bors retry

**Comment by mkroening** [comment]
bors retry

**Comment by mkroening** [comment]
bors retry

**Comment by mkroening** [comment]
bors cancel

**Comment by mkroening** [comment]
bors r=stlankes

**Comment by mkroening** [comment]
bors retry

**Comment by stlankes** [comment]
bors retry

**Comment by mkroening** [comment]
Turns out the name of the other job was wrong as well.

bors r=stlankes

**Pull request merged**
