### PR TITLE
Bump version of loader

### PR DESCRIPTION
**Pull request by CarlWachter**
I believe this is why the CI run is failing now, because the kernel was updated without also changing the loader.

### CODE REVIEW

**Comment by CarlWachter** [comment]
@jounathaen

**Comment by jounathaen** [comment]
The file ist not called `rusty-loader` anymore, but `hermit-loader`. That's why the CI fails

**Comment by CarlWachter** [comment]
You are absolutely right! Works now.

**Comment by jounathaen** [comment]
Thanks!

**Pull request merged**
